apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: immich
data:
  TZ: Europe/Athens

  # Postgres
  DB_HOSTNAME: immich-database
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_PORT: "5432"

  # Redis
  REDIS_HOSTNAME: immich-redis
  REDIS_PORT: "6379"

  # Machine Learning
  ML_HOST: immich-machine-learning
  ML_PORT: "3003"
