---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    smtp_password: AgBG6MnHsnaKbWcaLZOIWqn9YklmN0FLLE3j4rgb2Y5MWqaGt3QgQF5VALuTYcBUd39J6Rgjkk+c14j6lbe0rVg1u1fIzAs4QS6WYqGMnE0yof/YuIIu8jZG62T5Y6Aa6C9XM+ml5E/pWbn9gte1y2GHlFSyuwG6XKLnzNiRJOPWpOoWQ6I1/ZWWAel9CoANddT8DaucERDvmQpv4zY8LjKiuW0ffnMIXlT9HuBqRGATVbhAvdp62OBYtozj63ihveKiEObwEEi4hDMGdw7Q5PKBTAz4YLPKlwk98vHOc1t2Dbk21Xd9sVmlg5oM/1H2bsiCN0cihfx4U9Iln3wNp1ZTzw7/sltYjJKKQ0s+R+5RJcgEfOnbbddAxwIuZW4J1U4TMl/xssUiwT8XZJlUosMf7omaxH5LXavwCilgYc6zHb56yHtULGdnxxCUbu8V1LRAF3BnBmq4eGsBDKXEPN6b82OU9yZ7qjIW2JSO+yeVKunS+HRrzOuLSkYRh7VtEqM/IGywh8r3KAPhy5pZpOA6LQqi49Jcz4PRg+lqmq+IVWF7in/TuyNeF3zzLeDVWGr+faribOUdsk2QbUutr6CTEqqzR1y6FY7mkAhK8wDIugWTQ3D3+sH8rpEJOROWSJ4DIxQjLTevZ0SrMcWlObJjXv0n4taFgqQgimOwKU5GV7YVtBDgm6Eopaw3U5TjFk/BxRrA+z4W43iDluEv133mQzx9zQ==
    smtp_user: AgDTrKhrUTa6cRcOJJUh11ZO9snCGPWJv69vSSCbdjynR6ax0PTLD1m5TjOkvmajkLkniuAqqrU8sVeU1FDCQ32EpwCCcY5QBRErz6m80Tz+wNjsekse8OHm1DIobw+FSztC7M8YHJys7QV0ZBSXixalltCfKn3//ZJQiZ7RRVHAlWCgtXNtYpEe9OICVoGREBmoR0nkpAzeuwMhxjH/NI7FIGFHYmMwYquZtAmk8239z+F+ulvs9HeXJWf8s/Iv2a9daFhpbLkpnwf7yBi5QdPYd1fp45s0NLG6N0qbqB74iUNgeHswwRkAa7JnnaBUT9Nx8Bi15y3IaAo8MEUvILB27XS9dC/N98zCuXNb5dxcms3lb5qq1QiujluPp4OVYA8IqzieOwt0RMDvZx+Sn+WPJk4qqxIC5op8Jlo99nP+VqBL4c9KEI9LFeYchigfwdKGW4sH/cGpmurw/aRnM/f7ol9ygggYtqbGzXBdfkk8D1jzWU+VWGKaAGTAdHgkfSUD0qyVZ+1YLwWsVtB7Bu/mahhelTdmG7TWvusArUcb/fW9asrwKzAITRIHAeW5EP4IiPk8groayPWjZS7oYrfIb4+jkRCCOTVw3NgPaQDJ77QcprY6NuxkyCozfXv8UuD+RR/nQ4PhdZRzMxiVpC8Mm3G+APcHxYM/4DRtR+BPdgfcqQA9RlC2YdcWj+Fl7ioYrHPE4fNr0sQsq4GH3hhS9Cg=
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
    type: Opaque
