---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    SMTP_PASSWORD: AgC06K+TFS+xFhwS6ruNtktZjGi1Dr8A/FMR+xVCZNILWP0E+lKLpksTGpZAQndqksSeum6s3Q0hpAbxQx+fksQOkl5TG0VQvvuH1eL2ynI7+mJTUoCDgxQLtPJ1iqOl2YF+57gekw4hFXIIMKTd7f3GMS+Vd6EEjs8D2V+vAFB/YWPoHIlVufJ/h43BJzwc5qcUAuLnv4LeyD0QcK3HDhXMACbXR6Oi+qQVi3er0yqdVtDgQEB9yU6mksnpNFiNemK0MYm7W1k6tNvPyfkdNLCmYSEfo9ZkIQSAsg9pLmpkro8vp2R2AecrwOuH7spIaZmx07j5E4fJyPscr0GLhp7aUKz67bFL+GdXsSJEan7YNhLTls9N1DyrOpsOCvNtOTeZuQ9xAqvbEluekefmnlPFLT6Ad2acuSTvMdj4BznIpmC7LEak+4+jfZGK0wppOcdkKEbHV3M3OC0Q3xWG95grW7U+I93efM+QPRQPlc7+dV+m1JDBNUAOF/5pbw9NFcrsmWXoSDiONY14wCs+5R+s2maJoiTK9oMAhiK48Hw9Dg8mVBOWtHlv+2UQbWhrJAUpo6yCrfTGxWkYM1eMs6z4xLEH19f0GbGAzU5I8nW2dp0paOl1RcHayOgTUyPh9LlQEFKqKrjNe12R8VyKLAzJ9m6pIx4hiIPMIDWLV1VjDfdw2b8WeE1WuzHpTjgakWxwlkF/6moU6qYeRI1iXk8gqyOjlw==
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
    type: Opaque
