- name: Clone GitHub Repository
  hosts: k3s_api

  tasks:
    - name: Clone GitHub Repository
      ansible.builtin.git:
        repo: "https://github.com/manos-grigorakis/home-lab.git"
        dest: /home/manos/home-lab
        version: "main"
